version: 2

conda:
  environment: docs/environment.yml

build:
  image: latest
#  os: "ubuntu-20.04"
#  tools:
#    python: "mambaforge-4.10"
#
#  image: latest
#
#  os: "ubuntu-20.04"
#  tools:
#    python: "3.9"

python:
  # Install our python package before building the docs
  version: 3.8
  install:
    - method: pip
      path: .

